# Tên tệp: .github/workflows/frontend.yml
name: Triển khai Frontend (FE)

# Kích hoạt khi có sự kiện push lên nhánh main
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # CHỈ chạy khi có thay đổi trong thư mục 'frontend'

jobs:
  deploy_frontend:
    name: Triển khai FE qua FTP
    runs-on: ubuntu-latest
    
    # Môi trường nếu bạn cần (ví dụ: production)
    # environment:
    #   name: Production

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
      
      # ⚠️ BƯỚC BUILD (Chỉ cần nếu FE là React, Vue, Angular, v.v.)
      # Nếu là HTML/CSS/JS thuần, bạn có thể bỏ qua bước này.
      # Nếu dùng, bạn phải thay đổi 'local-dir' bên dưới thành thư mục build (ví dụ: ./frontend/build)
      - name: Cài đặt và Build (Ví dụ: React/Node)
        if: ${{ false }} # Đặt là 'true' nếu bạn cần build
        run: |
          npm install
          npm run build
        working-directory: ./frontend
        
      # ⬆️ BƯỚC TRIỂN KHAI QUA FTP
      - name: Triển khai FE lên Host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST_FE }}
          username: ${{ secrets.FTP_USERNAME_FE }}
          password: ${{ secrets.FTP_PASSWORD_FE }}
          port: 21 # Thay đổi nếu cổng FTP của bạn khác
          local-dir: ./frontend/ # Thư mục local chứa code FE (sau khi build nếu có)
          server-dir: /public_html/ # Thư mục đích trên host (thường là public_html)
          # delete-removed-files: true # Nếu muốn xóa các tệp bị xóa khỏi repo